import {useState} from 'react';
import {ArrowUpRight, ArrowLeft, FileText, HardDrive, Users, Download, Pause, Play, MessageSquare} from 'lucide-react';
import {company, reviews} from './data';

export function FeedbackStrip(){
  const [paused,setPaused]=useState(false);
  return <section className="feedback wrap" aria-labelledby="feedback-heading">
    <div className="feedback-heading"><div><p className="eyebrow">CUSTOMER FEEDBACK</p><h2 id="feedback-heading">Good work starts a conversation.</h2><p className="feedback-note">Feedback from Akshay, plus three clearly marked sample reviews awaiting real customer stories.</p></div><button type="button" className="feedback-toggle" aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={15}/>:<Pause size={15}/>}<span>{paused?'Resume':'Pause'} slideshow</span></button></div>
    <div className={`feedback-window${paused?' is-paused':''}`} tabIndex={0} aria-label="Customer feedback and labeled sample reviews. Hover or focus to pause scrolling."><div className="feedback-track">
      {[0,1].map(copy=><div className="feedback-group" key={copy} aria-hidden={copy===1?true:undefined}>{reviews.map(review=><article className={`feedback-card${review.sample?'':' verified-feedback'}`} key={review.id}><div className="feedback-card-top"><MessageSquare size={18}/><span>{review.sample?'SAMPLE · PLACEHOLDER':'CUSTOMER FEEDBACK'}</span></div><p className="feedback-text">{review.text}</p><div className="feedback-author"><h3>{review.title}</h3><span>{review.project}</span></div><span className="feedback-placeholder">{review.sample?'Illustrative only — not a real testimonial':'Feedback summarized from the client’s comments'}</span></article>)}</div>)}
    </div></div>
  </section>;
}

export function AboutPage(){
  return <>
    <section className="about-intro-page wrap section">
      <a href="/" className="text-link"><ArrowLeft size={16}/>Back to home</a>
      <p className="eyebrow">ABOUT SBM TECH SOLUTIONS</p><h1>Thoughtful software.<br/><em>A personal commitment.</em></h1>
      <p className="page-lead">A founder-led company bringing practical development to websites, software, and interactive experiences.</p>
    </section>
    <section className="founder-page-band"><div className="wrap founder-page-grid section">
      <figure className="founder-portrait"><img src="/images/sharveshwar.jpeg" alt="Sharveshwar S, founder of SBM Tech Solutions" width="402" height="520" fetchPriority="high"/><figcaption>Sharveshwar S <span>Founder & developer</span></figcaption></figure>
      <div className="founder-biography"><p className="eyebrow">MEET THE FOUNDER</p><h2>Hello, I’m<br/><em>Sharveshwar.</em></h2><p className="biography-lead">I enjoy turning a practical problem into something people can actually use.</p><p>I completed my B.Tech in Information Technology in 2026. My work spans Java, Spring Boot, React, and Unity, bringing together web development and interactive software.</p><p>During a 20-month AR/VR internship at Roche Pharma India, I worked as a Unity developer with C# and immersive experiences. That hands-on experience shapes how I approach each build: understand the need, develop carefully, and keep improving through feedback.</p><p>I started SBM Transformative Tech Solutions to offer that same direct, considered approach to founders and businesses. You work with the person developing your project, from the first discussion to the handover.</p><a href={company.portfolio} target="_blank" rel="noopener noreferrer" className="button">Explore my personal portfolio <ArrowUpRight size={17}/></a><small className="portfolio-access">The portfolio is currently an owner-only preview.</small></div>
    </div></section>
    <section className="wrap section about-principles"><div className="section-heading"><div><p className="eyebrow">OUR APPROACH</p><h2>Clear scope.<br/>Careful execution.</h2></div><p>A small company with a focused service offering and direct communication.</p></div><div className="principle-grid"><article><span>01</span><h3>Practical by choice</h3><p>Start with the workflow and the people who will use it. Choose the technology to suit the problem.</p></article><article><span>02</span><h3>Honest about the scope</h3><p>Agree requirements, milestones, and the estimate before work begins. Discuss changes as they arise.</p></article><article><span>03</span><h3>Built to hand over</h3><p>Make the agreed source, setup notes, and next steps clear so the project remains understandable.</p></article></div></section>
    <section className="page-cta"><div className="wrap"><div><p className="eyebrow">HAVE SOMETHING IN MIND?</p><h2>Let’s make it useful.</h2></div><a className="button light" href="/start-project/">Discuss your project <ArrowUpRight size={18}/></a></div></section>
  </>;
}

export function InvoicePreview(){return <div className="invoice-preview" aria-label="Illustrative invoice preview using fictional sample data"><div className="invoice-toolbar"><span><FileText size={15}/>Invoice workspace</span><span className="offline-pill">LOCAL & OFFLINE</span></div><div className="invoice-paper"><div className="invoice-paper-top"><span>INVOICE<small>ILLUSTRATIVE SAMPLE</small></span><span>No. INV-001</span></div><div className="invoice-parties"><span>FROM<strong>Example Properties</strong></span><span>BILL TO<strong>Sample Tenant</strong></span></div><div className="invoice-line"><span>Description</span><span>Amount</span></div><div className="invoice-line"><span>Monthly rent</span><span>₹10,000.00</span></div><div className="invoice-line"><span>CGST · 9%</span><span>₹900.00</span></div><div className="invoice-line"><span>SGST · 9%</span><span>₹900.00</span></div><div className="invoice-total"><span>Total</span><strong>₹11,800.00</strong></div><p>Fictional illustration. Tax rates are editable in the app.</p></div><div className="invoice-preview-footer"><span><HardDrive size={14}/>Stored on your device</span><span><FileText size={14}/>A4 PDF export</span></div></div>}

export function InvoicePage(){
  const features=[{icon:FileText,title:'Invoices & PDF export',text:'Create rental invoices with editable dates, financial-year numbering, and a matching A4 preview and PDF.'},{icon:Users,title:'Tenant & landlord records',text:'Keep reusable party details, choose the tenant for an invoice, and restore deleted tenant records.'},{icon:HardDrive,title:'Offline workspace',text:'Work locally in the Windows desktop app. The application does not require a backend or account.'},{icon:Download,title:'Backup & restore',text:'Export the workspace to a local backup, review a restore before applying it, and undo the last restore.'}];
  return <><section className="wrap section invoice-project"><a href="/#work" className="text-link"><ArrowLeft size={16}/>Back to projects</a><div className="invoice-project-grid"><div><p className="eyebrow">DESKTOP APPLICATION / WINDOWS</p><h1>Invoice Generator App</h1><p className="page-lead">A focused workspace for everyday rental invoicing. Create, preview, and export invoices with your records kept on your device.</p><p className="project-stack">REACT · VITE · ELECTRON · LOCAL STORAGE</p><a className="button" href={`mailto:${company.email}?subject=Invoice%20Generator%20App%20demo%20enquiry`}>Request a demonstration <ArrowUpRight size={16}/></a><p className="project-footnote">Project overview. The desktop application is available for demonstration on request.</p></div><InvoicePreview/></div></section><section className="project-feature-band"><div className="wrap section"><p className="eyebrow">WHAT IT DOES</p><h2>Less repetition.<br/>More useful tools.</h2><div className="project-features">{features.map(({icon:Icon,title,text})=><article key={title}><Icon size={23}/><h3>{title}</h3><p>{text}</p></article>)}</div><p className="project-disclosure">The illustration above uses fictional data. The app supports editable CGST and SGST rates; it does not determine which taxes apply. Data is stored locally and does not sync between devices.</p></div></section><section className="page-cta"><div className="wrap"><div><p className="eyebrow">A WORKFLOW OF YOUR OWN?</p><h2>Build tools around your business.</h2></div><a className="button light" href="/start-project/">Talk to us <ArrowUpRight size={18}/></a></div></section></>;
}
